<?php

const VIDEOJUEGO = "VIDEOJUEGO";
const JUE_ID = "JUE_ID";
const JUE_NOMBRE = "JUE_NOMBRE";
const JUE_GENERO = "JUE_GENERO";
const JUE_PLATAFORMA = "JUE_PLATAFORMA";
const JUE_MODIFICACION = "JUE_MODIFICACION";
const JUE_ELIMINADO = "JUE_ELIMINADO";

